recipe: default.v1
assistant_id: 20231220-162300-gold-pitch
language: zh
pipeline:
- name: rasa_custom_tokenizer.pkuseg_tokenizer.pkuseg #JiebaTokenizer, rasa_custom_tokenizer.tokenizer.MicroTokenizer
- name: LanguageModelFeaturizer
  model_name: bert
  model_weight: bert-base-chinese
  model_path: 
- name: DIETClassifier
  constrain_similarities: true
  epochs: 100
  learning_rate: 0.001
  tensorboard_log_directory: ./log
- name: EntitySynonymMapper
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: RulePolicy
